[build]
  command = "npm run build"
  publish = "build"
  
[build.environment]
  NODE_VERSION = "20.11.0"  # Updated to Node 20

# Branch deploy contexts
[context.develop]
  command = "npm run build"
  [context.develop.environment]
    REACT_APP_ENV = "develop"

[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    REACT_APP_ENV = "preview"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    REACT_APP_ENV = "preview"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# API routes - proxy to Netlify functions (order matters!)
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/grants/*"
  to = "/.netlify/functions/grants/:splat"
  status = 200

[[redirects]]
  from = "/api/grants"
  to = "/.netlify/functions/grants"
  status = 200

[[redirects]]
  from = "/api/chat/grants"
  to = "/.netlify/functions/chat"
  status = 200

# SPA routing for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better caching
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/data/*"
  [headers.values]
    cache-control = "public, max-age=300"

[[headers]]
  for = "*.html"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/videos/*"
  [headers.values]
    cache-control = "public, max-age=31536000"
    content-type = "video/mp4"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
